config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/post' => 'searchs#search', as: 'search'
  get   'users/:id/mypage'  => 'users#mypage', as: 'mypage'
  get 'users/:id/delete_image'  => 'users#delete_image', as: 'delete_image'
  get   'users/:id/cancel'  => 'users#cancel', as: 'cancel'
  get   'users/:id/post_index'  => 'users#post_index', as: 'post_index'
  get   'users/:id/favorite'  => 'favorites#index', as: 'favorite'
  get   'homes/score'  => 'homes#score', as: 'score'
  patch 'users/:id/quit'    => 'users#quit', as: 'quit'
  resources :users, only:[:index, :show, :edit, :update]
  resources :beers do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :beers, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  enum sex: { 男性: 0, 女性: 1 }
  enum favorite_style: { ラガー: 1, エール: 2, ハイブリッド: 3, その他: 4 }
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  delegate :pref_name, to: :prefecture
  attachment :profile_image

  def active_for_authentication?
    super && (is_deleted == false)
  end

  with_options presence: true do
    validates :name, length: { minimum: 1, maximum: 10 }, uniqueness: true
    validates :email, uniqueness: true
    validates :sex
    validates :birth_date
    validates :prefecture_id
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def after_sign_up_path_for(resource)
    flash[:notice] = '新規登録ありがとうございます！'
    mypage_path(resource)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  # 同じアカウントでは利用不可
  def reject_user
    @user = User.find_by(email: params[:user][:email])
    return if @user.nil?

    if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == true)
      flash[:notice] = '退会済みです。再度ご登録をしてご利用ください。'
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def mypage
    if user_signed_in?
      @user = User.find(params[:id])
    else
      flash[:notice] = 'こちらからご登録後に閲覧いただけます！'
      redirect_to new_user_registration_path
    end
  end

  def post_index
    @user = User.find_by(id: params[:id])
    @beers = @user.beers.order(created_at: :desc).page(params[:page]).per(10)
  end

  def index
    @users = User.order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    if user_signed_in?
      @user = User.find(params[:id])
      if current_user == @user
        @user = User.find(params[:id])
      else
        redirect_to mypage_path(current_user.id)
      end
    else
      flash[:notice] = 'こちらからご登録後に閲覧いただけます！'
      redirect_to new_user_registration_path
    end
  end

  def edit
    @user = User.find(params[:id])
    if current_user == @user
      @user = User.find(params[:id])
    else
      redirect_to mypage_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = '編集内容を保存しました！'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def delete_image
    @user = User.find(params[:id])
    @user.profile_image = nil
    @user.save!
    flash[:notice] = 'プロフィール画像を削除しました！'
    render action: 'edit'
    nil
  end

  def cancel; end

  def quit
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = 'ご利用いただきありがとうございました！またのお越しをお待ちしております！'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :birth_date, :sex, :prefecture_id, :favorite_style, :favorite_beer,
                                 :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/cancel.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="main-title col-md-11">
      <h2 class="page-title">
        <span class="beer">退会する</span>
      </h2>
      <div class="info">
        <h2 class="text-center">本当に退会しますか？</h2>
        <p class="text-center mt-4">
          退会すると、会員登録情報や<br>
          これまでの投稿履歴が閲覧できなくなります。<br>
          退会する場合は、「退会する」をクリックしてください。
        </p>
        <div class="row mt-4">
         <%= link_to '退会する', quit_path, method: :PATCH, data: {confirm: "本当に退会してもよろしいですか？"}, class: 'btn btn-danger mx-auto h3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="main-title col-md-11">
      <h2 class="page-title">
        <span class="beer">登録情報・プロフィールの変更</span>
      </h2>
      <%= render 'layouts/errors', obj: @user %>
      <%= form_with model: @user, local:true do |f| %>
      <div class="info">
        <table>
          <tbody>
            <tr>
              <th style="width: 50%;" class="t-head">ユーザー名</th>
              <td style="width: 50%;" class="t-body2">
                <em>10文字以内でご入力ください。</em><br>
                <%= f.text_field :name, autofocus: true, class: 'form-control' %>
              </td>
            </tr>
            <tr>
              <th style="width: 50%;" class="t-head">メールアドレス</th>
              <td style="width: 50%;" class="t-body2"><%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %></td>
            </tr>
            <tr>
              <th style="width: 50%;" class="t-head">生年月日</th>
              <td style="width: 50%;" class="t-body2"><%= f.date_select :birth_date, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 20), default: Date.new(1990, 1, 1) %></td>
            </tr>
            <tr>
              <th style="width: 50%;" class="t-head">性別</th>
              <td style="width: 50%; padding-bottom: 0;" class="t-body2">
                <%= f.label :男性 %>
                <%= f.radio_button :sex, :男性 %>
                <%= f.label :女性 %>
                <%= f.radio_button :sex, :女性 %>
              </td>
            </tr>
            <tr>
              <th style="width: 50%;" class="t-head">都道府県</th>
              <td style="width: 50%;" class="t-body2"><%= f.collection_select :prefecture_id, Prefecture.all, :id, :pref_name, {include_blank: "---"}, class: 'form-control' %></td>
            </tr>
          </tbody>
        </table>
        <br>
        <table>
          <tbody>
            <tr>
              <th class="t-head">プロフィール写真</th>
              <td class="t-body2">
                <% if @user.profile_image_id.present? %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 150, 150 %><br>
                  <%= link_to '削除', delete_image_path(@user), class: 'text-secondary' %><br>
                <% end %>
                <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
              </td>
            </tr>
            <tr>
              <th class="t-head">好きなビアスタイル</th>
              <td class="t-body2"><%= f.select :favorite_style, [["ラガー"], ["エール"], ["ハイブリッド"], ["その他"]], include_blank: "選択して下さい" %></td>
            </tr>
            <tr>
              <th class="t-head">お気に入りビール</th>
              <td class="t-body2"><%= f.text_area :favorite_beer, class: 'form-control' %></td>
            </tr>
            <tr>
              <th class="t-head">自己紹介・備考</th>
              <td class="t-body2"><%= f.text_area :introduction, class: 'form-control' %></td>
            </tr>
          </tbody>
        </table>
        <div class="row mt-4">
         <%= f.submit '登　録', class: 'btn btn-danger mx-auto h3' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row mx-auto pb-0">
    <div class="user-index-title col-md-11">
      <h2 class="page-title d-flex">
        <div class="beer col-6">ユーザー一覧</div>
      </h2>
    </div>
  </div>
</div>
<% if @users.total_count > 8 %>
<div class="row index-page-box col-6">
  <div class="mx-col-md-9 page-line">
    <div class="index-page-area">
      <P class="cmment-content"><%= paginate @users %></P>
    </div>
  </div>
</div>
<% end %>
<div class="user-index-area">
  <div class="d-flex flex-wrap mx-auto">
    <% @users.each do |user| %>
      <div class="index-list-box">
        <%= link_to mypage_path(user) do %>
          <div><%= attachment_image_tag user, :profile_image, :fill, 170, 170, fallback: "no_image.jpg", size:'170x170',  class: 'user-picture' %></div>
        <% end %>
        <div class="pt-2">
          <p class="user-name-index">
            &nbsp;&nbsp;<i class="fas fa-user"></i>
            <%= link_to mypage_path(user), class: 'text-black-50 border-bottom' do %>
              <%= user.name %>
            <% end %>
          </p>
        </div>
        <div class="index-style-box">
          <span class="index-beer-style">好きなビアスタイル</span><br>
          <% if user.favorite_style.present? %>
          &nbsp;&nbsp;<%= user.favorite_style %>
          <% else %>
          &nbsp;&nbsp;<span>なし</span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/mypage.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="main-title col-md-11">
      <h2 class="page-title">
        <% if current_user == @user %>
        <span class="beer">&nbsp;My&nbsp;ページ</span>
        <% else %>
        <span class="beer">ユーザーページ</span>
        <% end %>
      </h2>
      <div class="profileBox">
        <div class="profile">
          <div class="content">
            <div class="d-flex">
              <p class="col-md-4"><%= attachment_image_tag @user, :profile_image, :fill, 150, 150, fallback: "no_image.jpg", size:'150x150',  class: 'picture' %></p>
              <div class="col-md-6 mt-3"><strong class="text-danger"><%= @user.name %></strong>さん (<%= @user.pref_name %> <%= @user.sex %>)<br>
                 <p class="mt-2"><%= link_to "いいねリスト", favorite_path(@user), class: 'btn btn-outline-success' %></p>
                 <p class="mt-2"><%= link_to "投稿リスト", post_index_path(@user), class: 'btn btn-outline-danger' %></p>
              </div>
            </div>
            <% if @user.introduction.present? %>
              <div class="mypage-info col-md-11 mx-auto">
               <p><%= simple_format(@user.introduction) %></p>
              </div>
            <% end %>
          </div>
        </div>
        <h2 class="beer-style box-item">好きなビアスタイル</h2>
        <div class="col-md-11 mypage-favorite-style">
          <%= @user.favorite_style %>
        </div>
        <h2 class="favorite-beer box-item">お気に入りのビール</h2>
        <div class="col-md-11 mypage-favorite-beer">
          <%= simple_format(@user.favorite_beer) %>
        </div>
        <% if current_user == @user %>
          <p class="user-show">
            <%= link_to "登録情報・プロフィールの変更>>", user_path(@user), class: 'text-info' %>
            <br>※登録情報とプロフィールの編集はこちらより行えます。
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/post_index.html.erb
<div class="container">
  <div class="row mx-auto pb-5">
    <div class="main-title col-11 mb-0">
      <h2 class="index-title">
        <% if current_user == @user %>
        <span class="post">&nbsp;My&nbsp;投稿リスト</span>
        <% else %>
        <span class="post">ユーザー投稿一覧</span>
        <% end %>
      </h2>
      <% if @beers.present? %>
        <%= render 'beers/index', beers: @beers %>
      <% else %>
      　<h4 class="pl-4">まだ投稿されていません</h3>
      <% end %>
    </div>
    <% if @beers.total_count > 10 %>
      <div class="row user-comment-box ">
        <div class="mx-col-md-9 page-line">
          <div class="page-area">
            <P class="cmment-content"><%= paginate @beers %></P>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="main-title col-md-11">
      <h2 class="page-title">
        <span class="beer">登録内容変更</span>
      </h2>
      <div class="info">
        <div style="text-align:right;">
          <%= link_to ">>ユーザー情報を編集する", edit_user_path(@user), class: 'text-secondary' %>
        </div>
        <table>
          <tbody>
            <tr>
              <th style="width: 50%;" class="t-head">ユーザー名</th>
              <td style="width: 50%;" class="t-body2"><%= @user.name %></td>
            </tr>
            <tr>
              <th style="width: 50%;" class="t-head">メールアドレス</th>
              <td style="width: 50%;" class="t-body2"><%= @user.email %></td>
            </tr>
            <tr>
              <th style="width: 50%;" class="t-head">生年月日</th>
              <td style="width: 50%;" class="t-body2"><%= @user.birth_date.strftime('%Y/%m/%d') %></td>
            </tr>
            <tr>
              <th style="width: 50%;" class="t-head">性別</th>
              <td style="width: 50%;" class="t-body2"><%= @user.sex %></td>
            </tr>
            <tr>
              <th style="width: 50%;" class="t-head">都道府県</th>
              <td style="width: 50%;" class="t-body2"><%= @user.pref_name %></td>
            </tr>
          </tbody>
        </table>
        <br>
        <table>
          <tbody>
            <tr>
              <th class="t-head">プロフィール写真</th>
              <td class="t-body2"><%= attachment_image_tag @user, :profile_image, :fill, 150, 150 %></td>
            </tr>
            <tr>
              <th class="t-head">好きなビアスタイル</th>
              <td class="t-body2"><%= @user.favorite_style %></td>
            </tr>
            <tr>
              <th class="t-head">お気に入りビール</th>
              <td class="t-body2"><%= simple_format(@user.favorite_beer) %></td>
            </tr>
            <tr>
              <th class="t-head">自己紹介・備考</th>
              <td class="t-body2"><%= simple_format(@user.introduction) %></td>
            </tr>
          </tbody>
        </table>
        <div style="text-align: left; margin-top: 6px;">
          <%= link_to "退会する>>", cancel_path(@user), class: 'text-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>