config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/post' => 'searchs#search', as: 'search'
  get   'users/:id/mypage'  => 'users#mypage', as: 'mypage'
  get 'users/:id/delete_image'  => 'users#delete_image', as: 'delete_image'
  get   'users/:id/cancel'  => 'users#cancel', as: 'cancel'
  get   'users/:id/post_index'  => 'users#post_index', as: 'post_index'
  get   'users/:id/favorite'  => 'favorites#index', as: 'favorite'
  get   'homes/score'  => 'homes#score', as: 'score'
  patch 'users/:id/quit'    => 'users#quit', as: 'quit'
  resources :users, only:[:index, :show, :edit, :update]
  resources :beers do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
  enum style: { ラガー: 1, エール: 2, ハイブリッド: 3, その他: 4 }, _prefix: true
  enum retailer: { 専門店: 1, コンビニ・スーパー: 2, 通販サイト: 3, その他: 4 }, _prefix: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(word)
    @beer = Beer.where('name LIKE?', "%#{word}%")
  end

  with_options presence: true do
    validates :name, length: { minimum: 1, maximum: 15 }
    validates :style
    validates :retailer
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def new
    @beer = Beer.new
  end

  def create
    @beer = current_user.beers.new(beer_params)
    @beer.user_id = current_user.id
    if @beer.save
      flash[:notice] = '投稿が完了しました！'
      redirect_to beer_path(@beer.id)
    else
      render :new
    end
  end

  def index
    @beers = Beer.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    if user_signed_in?
      @beer = Beer.find(params[:id])
      @comments = @beer.post_comments.all.order(created_at: :desc).page(params[:page]).per(10)
      @average = PostComment.where(beer_id: @beer.id).average(:rate)
      @average = 0 if @average.nil?
      @user = @beer.user
      @post_comment = PostComment.new
    else
      flash[:notice] = 'こちらからご登録後に閲覧いただけます！'
      redirect_to new_user_registration_path
    end
  end

  def edit
    @beer = Beer.find(params[:id])
    if current_user == @beer.user
      @beer = Beer.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @beer = Beer.find(params[:id])
    if @beer.update(beer_params)
      flash[:notice] = '投稿内容を更新しました！'
      redirect_to beer_path(@beer)
    else
      render :edit
    end
  end

  def destroy
    @beer = Beer.find(params[:id])
    if current_user == @beer.user
      @beer.destroy
      flash[:notice] = '投稿を削除しました！'
      redirect_to beers_path
    else
      redirect_to root_path
    end
  end

  private

  def beer_params
    params.require(:beer).permit(:name, :feature, :style, :retailer, :origin, :abv, :image, :explanation)
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_index.html.erb
<div class="list-box">
  <% beers.each do |beer| %>
    <div class="list-item">
      <div class="list-beer-image">
        <%= link_to beer_path(beer.id), 'data-turbolinks': false do %>
         <%= attachment_image_tag beer, :image, :fill, 130, 120, fallback: "no_image.jpg", size:'130x120', class: 'index-picture' %>
        <% end %>
      </div>
      <div class="col-10">
        <div class="col-9">
          <div class="item-title">
            &ensp;<i class="fas fa-beer text-warning"></i>
            <%= link_to beer_path(beer.id), class: 'text-black-50 border-bottom' do %>
              <%= beer.name %>
            <% end %>
          </div>
        </div>
        <div class="index-text-box col-6">
          <div class="index-beer-feature">
            <p class="index-point-title">&nbsp;✔️ ポイント
              <%= link_to mypage_path(beer.user), class: 'text-black-50 border-bottom' do %>
              <span class="index-user-name">&nbsp;by&thinsp;<%= beer.user.name %></span>
              <% end %>
            </p>
            <% if beer.feature.present? %>
            <p class="index-point-text"><%= beer.feature %></p>
            <% else %>
            <p class="index-point-text">なし</p>
            <% end %>
          </div>
        </div>
        <div class="index-text-box-2 col-6">
          <% if beer.post_comments.present? %>
          <div class="index-score-box">評価：<span class="index-beer-score"><%= beer.post_comments.where(beer_id: beer.id).average(:rate).floor(1) %></span><span class="index-max-score">&thinsp;/５点中</span></div>
          <% else %>
          <div class="index-score-box">評価：<span class="index-beer-score">まだ評価されていません</span></div>
          <% end %>
          <div class="index-score-count mt-1"><%= beer.post_comments.count %>件のレビュー</div>
          <div class="index-create text-black-50"><%= beer.created_at.strftime('%Y/%m/%d %H:%M:%S') %> 投稿</div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/beers/edit.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="main-title col-md-11 info mt-4">
      <h2 class="page-title">
        <span class="new">投稿内容編集</span>
      </h2>
      <%= render 'layouts/errors', obj: @beer %>
      <%= form_with model: @beer, local:true do |f| %>
      <div>
        <table>
          <tbody>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :name, "ビール名" %></th>
              <td style="width: 85%;" class="t-body2">
                <em>15文字以内でご入力ください。</em><br>
                <%= f.text_field :name, class: 'form-control' %>
              </td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :feature, "おすすめポイント" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.text_field :feature, class: 'form-control' %></td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :style, "ビールスタイル" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.select :style, [["ラガー"], ["エール"], ["ハイブリッド"], ["その他"]], include_blank: "選択して下さい" %></td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :retailer, "購入場所" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.select :retailer, [["専門店"], ["コンビニ・スーパー"], ["通販サイト"], ["その他"]], include_blank: "選択して下さい" %></td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :origin, "原産国" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.text_field :origin, class: 'form-control' %></td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :abv, "度数" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.text_field :abv %> ％</td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :image_id, "ビール画像" %></th>
              <td style="width: 85%;" class="t-body2">
                <%= f.attachment_field :image, placeholder: "ビール画像" %><br>
                <div id="new-image"></div>
                <%= attachment_image_tag @beer, :image, :fill, 180, 170, class: 'mt-2' %>
              </td>
            </tr>
          </tbody>
        </table>
        <section>
          <h2 class="explanation mb-0"><%= f.label :explanation, "紹介文" %></h2>
          <p class="pl-2 m-0 ">感想や詳細などがあればお書きください。(右下の外枠から枠を広げることができます)</p>
          <div class="field">
            <%= f.text_area :explanation, class: 'form-control' %>
          </div>
        </section>
        <div class="row mt-4">
         <%= f.submit '保　存', class: 'btn btn-danger mx-auto h3' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/beers/index.html.erb
<div class="container">
  <div class="row mx-auto pb-5">
    <div class="main-title col-11 mb-0">
      <h2 class="index-title">
        <span class="post">ユーザー投稿一覧</span>
      </h2>
      <% if @beers.present? %>
        <%= render 'beers/index', beers: @beers %>
      <% else %>
      　<h4 class="pl-4">まだ投稿されていません</h3>
      <% end %>
    </div>
    <% if @beers.total_count > 10 %>
      <div class="row user-comment-box ">
        <div class="mx-col-md-9 page-line">
          <div class="page-area">
            <P class="cmment-content"><%= paginate @beers %></P>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/beers/new.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="main-title col-md-11 info mt-4">
      <h2 class="page-title">
        <span class="new">新規投稿</span>
      </h2>
      <%= render 'layouts/errors', obj: @beer %>
      <%= form_with model: @beer, local:true do |f| %>
      <div>
        <table>
          <tbody>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :name, "ビール名" %></th>
              <td style="width: 85%;" class="t-body2">
                <em>15文字以内でご入力ください。</em><br>
                <%= f.text_field :name, class: 'form-control' %>
              </td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :feature, "おすすめポイント" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.text_field :feature, class: 'form-control' %></td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :style, "ビールスタイル" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.select :style, [["ラガー"], ["エール"], ["ハイブリッド"], ["その他"]], include_blank: "選択して下さい" %></td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :retailer, "購入場所" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.select :retailer, [["専門店"], ["コンビニ・スーパー"], ["通販サイト"], ["その他"]], include_blank: "選択して下さい" %></td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :origin, "原産国" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.text_field :origin, class: 'form-control' %></td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :abv, "度数" %></th>
              <td style="width: 85%;" class="t-body2"><%= f.text_field :abv %> ％</td>
            </tr>
            <tr>
              <th style="width: 25%;" class="t-head2"><%= f.label :image_id, "ビール画像" %></th>
              <td style="width: 85%;" class="t-body2">
                <%= f.attachment_field :image, placeholder: "ビール画像" %>
                <div id="new-image"></div>
              </td>
            </tr>
          </tbody>
        </table>
        <section>
          <h2 class="explanation mb-0"><%= f.label :explanation, "紹介文" %></h2>
          <p class="pl-2 m-0 ">感想や詳細などがあればお書きください。(右下の外枠から枠を広げることができます)</p>
          <div class="field">
            <%= f.text_area :explanation, class: 'form-control' %>
          </div>
        </section>
        <div class="row mt-4">
         <%= f.submit '投　稿', class: 'btn btn-danger mx-auto h3' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/beers/show.html.erb
<div class="container pb-5">
  <div class="row mx-auto" style="margin-bottom: 40px;">
    <div class="col-md-12">
      <div class="details col-md-11">
        <div class="details-box">
          <div id="beer_<%= @beer.id %>">
            <div class="head d-flex">
              <h2 class="headline ml-4"><i class="fas fa-beer text-warning"></i> <%= @beer.name %></h2>
              <p class="favorite-btn"><%= render 'favorites/favorite-btn', beer: @beer %></p>
            </div>
            <ul class="line">
              <li>
                <span class="bg-info text-center text-white p-1 mr-1">ユーザー名</span>
                <%= link_to mypage_path(@beer.user), class: 'text-black-50 border-bottom' do %>
                 <%= @beer.user.name %>さん
                <% end %>
              </li>
              <li><span class="bg-info text-center text-white p-1 mr-2">スタイル</span><%= @beer.style %></li>
              <li><span class="bg-info text-center text-white p-1 mr-2">購入場所</span><%= @beer.retailer %></li>
              <li class="time"><%= @beer.created_at.strftime('%Y/%m/%d %H:%M:%S') %> 投稿</li>
            </ul>
          </div>
          <div class="content-box">
            <div class="image-box">
              <div class="beer-image"><%= attachment_image_tag @beer, :image, :fill, 370, 370, fallback: "no_image.jpg", size:'370x370',class: 'show-image-picture' %></div>
            </div>
            <div class="beer-text">
              <div class="point">
                <p class="point-title">&nbsp;✔️ ポイント</p>
                <% if @beer.feature.present? %>
                <p class="point-text"><%= @beer.feature %></p>
                <% else %>
                <p class="point-text ml-4">なし</p>
                <% end %>
              </div>
              <table>
                <tbody>
                  <tr>
                    <th class="t-head2">原産国</th>
                    <td class="t-body2"><%= @beer.origin %></td>
                  </tr>
                  <tr>
                    <th class="t-head2">アルコール度数</th>
                    <% if @beer.abv.present? %>
                    <td class="t-body2"><%= @beer.abv %>&nbsp;%</td>
                    <% else %>
                    <td class="t-body2"><%= @beer.abv %></td>
                    <% end %>
                  </tr>
                </tbody>
              </table>
              <div class="score-box">
                <div class="score-head">
                  <h2 class="score-title">&nbsp;<i class="fas fa-users"></i>&nbsp;ユーザーレビュー</h2>
                  <div class="average-box">
                    <div id="star-rate-<%="average"%>"></div>
                    <div class="average-font">(平均)</div>
                  </div>
                  <div class="average-text">星５つ中の <%= @average.floor(1).to_f %></div>
                </div>
              </div>
            </div>
          </div>
          <% if @beer.explanation.present? %>
            <div class="introduction mt-3">
              <h2 class="text-title">紹介文</h2>
              <div class="text-box">
                <P class="mt-0 mb-0"><%= simple_format(@beer.explanation) %></P>
              </div>
            </div>
          <% end %>
          <% if current_user == @user %>
            <div class="d-flex mt-4">
              <p class="mx-auto"><%= link_to "編　集", edit_beer_path(@beer), class: 'btn btn-success' %></p>
              <p class="mx-auto"><%= link_to '削　除', beer_path(@beer), method: :delete, data:{ confirm: "本当に削除しますか？" }, class: 'btn btn-danger' %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% if current_user != @user %>
    <div class="row comment-box">
      <div class="main-title col-md-9 comment-set">
        <h2 class="comment-title">
          <span class="new">投稿の感想やコメントを伝えよう <i class="far fa-comment-dots"></i></span>
        </h2>
        <%= form_with model:[@beer,@post_comment] do |f| %>
          <div class="commment-back">
            <div class="d-flex pt-2">
              <div class="star-text"><%= f.label :rate,'評 価', class:'rate-title' %></div>
              <div id="star">
                <span class="rate-star"><%= f.hidden_field :rate, id: :review_star %></span>
              </div>
            </div>
            <div class="post-comment-area">
              <%= f.text_area :comment, placeholder: "コメントを入力", class: 'form-control' %>
            </div>
            <div class="row mt-3">
             <%= f.submit '投　稿', class: 'btn btn-danger mx-auto h3' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div id="beer_<%= @beer.id %>">
    <div class="row user-comment-box">
      <div class="col-md-9 user-comment-set">
        <h2 class="user-comment-title">
          <span class="comments-count">コメント<%= @beer.post_comments.count %>件</span> <i class="far fa-comment-dots"></i>
        </h2>
      </div>
    </div>
    <div class="post_comments">
      <%= render 'post_comments/index', comments: @comments, beer_id: @beer.id %>
    </div>
  </div>
</div>

<!--コメント投稿フォームのスクリプト-->
<script>
　$('#star').empty();
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'post_comment[rate]',
    half: true,
  });
</script>

<!--評価の平均値のスクリプト-->
<script>
  $('#star-rate-<%="average"%>').empty();
  $('#star-rate-<%="average"%>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= @average %>,
  });
</script>