config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/post' => 'searchs#search', as: 'search'
  get   'users/:id/mypage'  => 'users#mypage', as: 'mypage'
  get 'users/:id/delete_image'  => 'users#delete_image', as: 'delete_image'
  get   'users/:id/cancel'  => 'users#cancel', as: 'cancel'
  get   'users/:id/post_index'  => 'users#post_index', as: 'post_index'
  get   'users/:id/favorite'  => 'favorites#index', as: 'favorite'
  get   'homes/score'  => 'homes#score', as: 'score'
  patch 'users/:id/quit'    => 'users#quit', as: 'quit'
  resources :users, only:[:index, :show, :edit, :update]
  resources :beers do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    word = params[:word]
    @word = word
    beer_ids = Beer.search(word)
    @sort = params[:keyword]

    beers = if @sort == 'many'
              beer_ids.includes(:post_comments).sort { |a, b| b.post_comments.size <=> a.post_comments.size }
            elsif @sort == 'likes'
              beer_ids.includes(:favorites).sort { |a, b| b.favorites.size <=> a.favorites.size }
            elsif @sort == 'old'
              beer_ids.order(created_at: :asc)
            else
              beer_ids.order(created_at: :desc)
            end
    @beers = Kaminari.paginate_array(beers).page(params[:page]).per(10)
  end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/search.html.erb
<div class="container">
  <div class="row mx-auto pb-5">
    <div class="main-title col-11 mb-0">
      <h2 class="index-title">
        <span class="post">検索結果</span>
      </h2>
      <div class="search-text">
        <% if @word.present? %>
        <div class="search-word">検索ワード:&thinsp;<%= @word %></div>
        <% else %>
        <div class="search-word">検索ワード:&nbsp;なし</div>
        <% end %>
        <% if @sort == "old" %>
        <div class="search-key">投稿が古い順</div>
        <% elsif @sort == "many" %>
        <div class="search-key">コメントが多い順</div>
        <% elsif @sort == "likes" %>
        <div class="search-key">いいねが多い順</div>
        <% else %>
        <div class="search-key">投稿が新しい順</div>
        <% end %>
      </div>
      <% if @beers.present? %>
        <% if @sort == "likes" %>
          <div class="list-box">
            <% @beers.each do |beer| %>
              <div class="list-item">
                <div class="list-beer-image">
                  <%= link_to beer_path(beer.id), 'data-turbolinks': false do %>
                   <%= attachment_image_tag beer, :image, :fill, 130, 120, fallback: "no_image.jpg", size:'130x120', class: 'index-picture' %>
                  <% end %>
                </div>
                <div class="col-10">
                  <div class="col-9">
                    <div class="item-title">
                      <span class="favorit-search">&ensp;❤️ <%= beer.favorites.count %></span>
                      <%= link_to beer_path(beer.id), class: 'text-black-50 border-bottom' do %>
                        <%= beer.name %>
                      <% end %>
                    </div>
                  </div>
                  <div class="index-text-box col-6">
                    <div class="index-beer-feature">
                      <p class="index-point-title">&nbsp;✔️ ポイント
                        <%= link_to mypage_path(beer.user), class: 'text-black-50 border-bottom' do %>
                        <span class="index-user-name">&nbsp;by&thinsp;<%= beer.user.name %></span>
                        <% end %>
                      </p>
                      <% if beer.feature.present? %>
                      <p class="index-point-text"><%= beer.feature %></p>
                      <% else %>
                      <p class="index-point-text">なし</p>
                      <% end %>
                    </div>
                  </div>
                  <div class="index-text-box-2 col-6">
                    <% if beer.post_comments.present? %>
                    <div class="index-score-box">評価：<span class="index-beer-score"><%= beer.post_comments.where(beer_id: beer.id).average(:rate).floor(1) %></span><span class="index-max-score">&thinsp;/５点中</span></div>
                    <% else %>
                    <div class="index-score-box">評価：<span class="index-beer-score">まだ評価されていません</span></div>
                    <% end %>
                    <div class="index-score-count mt-1"><%= beer.post_comments.count %>件のレビュー</div>
                    <div class="index-create text-black-50"><%= beer.created_at.strftime('%Y/%m/%d %H:%M:%S') %> 投稿</div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
        <%= render 'beers/index', beers: @beers %>
        <% end %>
      <% else %>
      　<h4 class="pl-4">該当する投稿は見つかりませんでした</h3>
      <% end %>
    </div>
    <% if @beers.total_count > 10 %>
      <div class="row user-comment-box ">
        <div class="mx-col-md-9 page-line">
          <div class="page-area">
            <P class="cmment-content"><%= paginate @beers %></P>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>