config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/post' => 'searchs#search', as: 'search'
  get   'users/:id/mypage'  => 'users#mypage', as: 'mypage'
  get 'users/:id/delete_image'  => 'users#delete_image', as: 'delete_image'
  get   'users/:id/cancel'  => 'users#cancel', as: 'cancel'
  get   'users/:id/post_index'  => 'users#post_index', as: 'post_index'
  get   'users/:id/favorite'  => 'favorites#index', as: 'favorite'
  get   'homes/score'  => 'homes#score', as: 'score'
  patch 'users/:id/quit'    => 'users#quit', as: 'quit'
  resources :users, only:[:index, :show, :edit, :update]
  resources :beers do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "箇所") %> の入力に誤りがあります。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerChoice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=360,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrap">
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark ">
          <%= link_to root_path, class: 'navbar-brand' do %>
           <h1 class="title">Beer Choice</h1>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <!-- ログインしている時 -->
                <div class="navbar-nav">
                  <div class="hamburger-menu">
                    <input type="checkbox" id="menu-btn-check">
                    <label for="menu-btn-check" class="menu-btn"><span></span></label>
                    <div class="menu-content">
                      <ul>
                        <li><h3>投稿検索</h3></li>
                        <li>
                          <%= form_tag(search_path, method: :get) do %>
                            <%= text_field_tag 'word', '', placeholder: "ビール名を入力", class: 'search-box' %><br>
                            <div class="pt-1"><%= select_tag 'keyword', options_for_select([['投稿が新しい順', 'new'], ['投稿が古い順', 'old'], ['コメントが多い順', 'many'], ['いいねが多い順', 'likes']]), class: 'key-search-btn' %></div>
                            <div class="pt-1"><%= submit_tag '検索', class: 'search-btn' %></div>
                          <% end %>
                        </li>
                        <li>
                          <div class="mt-2"><%= link_to "新規投稿 >>", new_beer_path, :style =>"color:white;" %></div>
                        </li>
                        <li>
                          <div><%= link_to "投稿リスト", post_index_path(current_user), :style =>"color:white;" %></div>
                        </li>
                        <li>
                          <div><%= link_to "いいねリスト", favorite_path(current_user), :style =>"color:white;" %></div>
                        </li>
                        <li>
                          <div><%= link_to "ランキングへ", score_path, :style =>"color:white;" %></div>
                        </li>
                        <li>
                          <div class="mt-5 pt-5"><%= link_to "マイページへ", mypage_path(current_user), :style =>"color:white;" %></div>
                        </li>
                        <li>
                          <div><%= link_to "ログアウト", destroy_user_session_path, method: :delete, :style =>"color:white;" %></div>
                        </li>
                  　   </ul>
                    </div>
                  </div>
                  <li class="nav-item">
                    <%= link_to "マイページ", mypage_path(current_user), :style =>"color:white;" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ビール投稿一覧", beers_path, :style =>"color:white;" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "投稿者一覧", users_path, :style =>"color:white;"%>
                  </li>
              <% else %>
              <!-- ログインしてない時 -->
                  <div class="navbar-nav mr-4">
                    <li class="nav-item pl-1">
                      <%= link_to "新規登録", new_user_registration_path, :style =>"color:white;" %>
                    </li>
                    <li class="nav-item mr-1">
                      <%= link_to "ログイン", new_user_session_path, :style =>"color:white;"%>
                    </li>
                  </div>
                </div>
              <% end %>
            </ul>
          </div>
        </nav>
      </header>
      <!--サクセスメッセージ-->
      <% if flash[:notice] %>
        <div class="alert alert-primary mb-0" role="alert"><strong><%= notice %></strong></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger mb-0" role="alert"><strong><%= alert %></strong></div>
      <% end %>
      <% if flash[:error] %>
        <div class="alert alert-danger mb-0" role="alert"><strong><%= flash[:error] %></strong></div>
      <% end %>
      <main>
       <%= yield %>
      </main>
      <footer class="bg-danger text-white">
       <div>
         <p class="text-center">Copyright © 2021 BeerChoice All rights reserved.</p>
       </div>
      </footer>
    </div>
  </body>
</html>